version: '3.2'
services:
    db:
        image: mariadb:latest
        ports:
            - 3306:3306
        deploy:
            replicas: 1
            placement:
              constraints:
              - node.role == worker
        volumes:
            - /mnt/nfsshare/docker/moodle/mariadb_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: m00dle
            MYSQL_DATABASE: moodle
            MYSQL_USER: tegar
            MYSQL_PASSWORD: m00dle
        networks:
            - moodle

    app:
        depends_on:
            - db
        image: tegarshndrn/moodle:latest
        ports:
            - "82:80"
        restart: always
        deploy:
            replicas: 2
            placement:
              constraints:
              - node.role == worker
        volumes:
            - /mnt/nfsshare/docker/moodle/moodle_data:/var/lib/html
        networks:
            - moodle

volumes:
    mariadb_data:
    moodle_data:

networks:
    moodle:

